/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./components/AppConfig.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppTopbar: typeof import('./components/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ProductOverviewWidget: typeof import('./components/dashboard/ProductOverviewWidget.vue')['default']
    RecentActivityWidget: typeof import('./components/dashboard/RecentActivityWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendWidget: typeof import('./components/dashboard/SalesTrendWidget.vue')['default']
    StatsWidget: typeof import('./components/dashboard/StatsWidget.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
