name: Deploy Vue site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Node.js를 설치합니다. 캐시 설정은 잠시 제거합니다.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # --- 가장 중요: 모든 작업을 하나의 단계로 합칩니다. ---
      - name: Install dependencies and Build Project
        run: |
          # 1. 'stock' 폴더로 이동합니다.
          cd stock
          
          # 2. 이동한 폴더에서 의존성을 설치합니다.
          npm install
          
          # 3. 이동한 폴더에서 프로젝트를 빌드합니다.
          npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # 업로드할 경로는 './stock/dist'가 맞습니다.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './stock/dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4